<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StadiumsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('stadia')->insert([
            /*[
                'name' => 'The Big House',
                'full_name' => 'Michigan Stadium',
                'address' => '1201 S Main St, Ann Arbor, MI 48104, Estados Unidos',
                'city' => 'Ann Arbor',
                'state' => 'Michigan',
                'stadium_rating' => 14,
                'zip_code' => null,
                'latitude' => 42.265835,
                'longitude' => -83.748695,
                'capacity' => 107601,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ohio Stadium',
                'full_name' => 'Ohio Stadium',
                'address' => '411 Woody Hayes Dr, Columbus, OH 43210, Estados Unidos',
                'city' => 'Columbus',
                'state' => 'Ohio',
                'stadium_rating' => 14,
                'zip_code' => '43210',
                'latitude' => 40.001667,
                'longitude' => -83.019722,
                'capacity' => 102780,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Beaver Stadium',
                'full_name' => 'Beaver Stadium',
                'address' => '1 Beaver Stadium, University Park, PA 16802, Estados Unidos',
                'city' => 'University Park',
                'state' => 'Pennsylvania',
                'stadium_rating' => 14,
                'zip_code' => '16802',
                'latitude' => 40.8122,
                'longitude' => -77.8561,
                'capacity' => 106572,
                'created_at' => now(),
                'updated_at' => now(),
            ],*/
            [
                'name' => 'Camp Randall Stadium',
                'full_name' => 'Camp Randall Stadium',
                'address' => '1440 Monroe St, Madison, WI 53711, Estados Unidos',
                'city' => 'Madison',
                'state' => 'Wisconsin',
                'country' => 'United States',
                'stadium_rating' => 14,
                'zip_code' => '53711',
                'latitude' => 43.0711,
                'longitude' => -89.4125,
                'capacity' => 80000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kinnick Stadium',
                'full_name' => 'Kinnick Stadium',
                'address' => '825 Stadium Dr, Iowa City, IA 52242, Estados Unidos',
                'city' => 'Iowa City',
                'state' => 'Iowa',
                'country' => 'United States',
                'stadium_rating' => 14,
                'zip_code' => '52242',
                'latitude' => 41.6588,
                'longitude' => -91.5511,
                'capacity' => 70585,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Spartan Stadium',
                'full_name' => 'Spartan Stadium',
                'address' => '325 W Shaw Ln, East Lansing, MI 48824, Estados Unidos',
                'city' => 'East Lansing',
                'state' => 'Michigan',
                'country' => 'United States',
                'stadium_rating' => 14,
                'zip_code' => '48824',
                'latitude' => 42.7286,
                'longitude' => -84.4844,
                'capacity' => 75705,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Memorial Stadium',
                'full_name' => 'Memorial Stadium',
                'address' => '1402 S 1st St, Champaign, IL 61820, Estados Unidos',
                'city' => 'Champaign',
                'state' => 'Illinois',
                'country' => 'United States',
                'stadium_rating' => 14,
                'zip_code' => '61820',
                'latitude' => 40.0961,
                'longitude' => -88.2367,
                'capacity' => 60470,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Memorial Stadium',
                'full_name' => 'Memorial Stadium',
                'address' => '1 Memorial Stadium Dr, Bloomington, IN 47408, Estados Unidos',
                'city' => 'Bloomington',
                'state' => 'Indiana',
                'country' => 'United States',
                'stadium_rating' => 14,
                'zip_code' => '47408',
                'latitude' => 39.1801,
                'longitude' => -86.5254,
                'capacity' => 52726,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ryan Field',
                'full_name' => 'Ryan Field',
                'address' => '1501 Central St, Evanston, IL 60208, Estados Unidos',
                'city' => 'Evanston',
                'state' => 'Illinois',
                'country' => 'United States',
                'stadium_rating' => 14,
                'zip_code' => '60208',
                'latitude' => 42.0569,
                'longitude' => -87.6775,
                'capacity' => 47130,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SHI Stadium',
                'full_name' => 'SHI Stadium',
                'address' => '1 Scarlet Knight Way, Piscataway, NJ 08854, Estados Unidos',
                'city' => 'Piscataway',
                'state' => 'New Jersey',
                'country' => 'United States',
                'stadium_rating' => 14,
                'zip_code' => '08854',
                'latitude' => 40.5136,
                'longitude' => -74.4657,
                'capacity' => 52754,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Memorial Stadium',
                'full_name' => 'Memorial Stadium',
                'address' => '600 Stadium Dr, Lincoln, NE 68588, Estados Unidos',
                'city' => 'Lincoln',
                'state' => 'Nebraska',
                'country' => 'United States',
                'stadium_rating' => 14,
                'zip_code' => '68588',
                'latitude' => 40.8201,
                'longitude' => -96.7056,
                'capacity' => 85458,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TCF Bank Stadium',
                'full_name' => 'Huntington Bank Stadium',
                'address' => '420 SE 23rd Ave, Minneapolis, MN 55455, Estados Unidos',
                'city' => 'Minneapolis',
                'state' => 'Minnesota',
                'country' => 'United States',
                'stadium_rating' => 14,
                'zip_code' => '55455',
                'latitude' => 44.974,
                'longitude' => -93.2267,
                'capacity' => 50805,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ross-Ade Stadium',
                'full_name' => 'Ross-Ade Stadium',
                'address' => '850 Steven Beering Dr, West Lafayette, IN 47906, Estados Unidos',
                'city' => 'West Lafayette',
                'state' => 'Indiana',
                'country' => 'United States',
                'stadium_rating' => 14,
                'zip_code' => '47906',
                'latitude' => 40.427,
                'longitude' => -86.918,
                'capacity' => 57336,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HighPoint.com Stadium',
                'full_name' => 'HighPoint.com Stadium',
                'address' => '1 Stadium Dr, East Rutherford, NJ 07073, Estados Unidos',
                'city' => 'East Rutherford',
                'state' => 'New Jersey',
                'country' => 'United States',
                'stadium_rating' => 14,
                'zip_code' => '07073',
                'latitude' => 40.8135,
                'longitude' => -74.074,
                'capacity' => 82500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Add more stadiums here based on the CSV data
        ]);
    }
}
